SELECT SUM(1) AS "cnt:TEMP(row count)(290714814)(0):qk"
FROM "Extract"."Extract" "Extract"
HAVING (COUNT(1) > 0)
/* { "tableau-query-origins": { "query-category": "RowCount", "lqctx-root-activity-id": "DlLRnHXxUkwIte5QkHjfFI" } } */;
SELECT CAST(TRUNC(EXTRACT(HOUR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) AS "hr:time:ok"
FROM "Extract"."Extract" "Extract"
GROUP BY 1
/* { "tableau-query-origins": { "query-category": "QuickFilter", "lqctx-root-activity-id": "Gqr1hvWvESOK1KqKUa2xHV", "lqctx-batch-query-id": "0" } } */;
SELECT CAST(TRUNC(EXTRACT(HOUR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) AS "TEMP(Domain)"
FROM "Extract"."Extract" "Extract"
GROUP BY 1
LIMIT 32
/* { "tableau-query-origins": { "query-category": "Unknown", "lqctx-root-activity-id": "FdvGQcJikzAKCnoSfwIrR+" } } */;
SELECT (((CAST(TRUNC(EXTRACT(YEAR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) * 10000) + (CAST(TRUNC(EXTRACT(MONTH FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) * 100)) + CAST(TRUNC(EXTRACT(DAY FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL)) AS "TEMP(Domain)"
FROM "Extract"."Extract" "Extract"
GROUP BY 1
LIMIT 32
/* { "tableau-query-origins": { "query-category": "Unknown", "lqctx-root-activity-id": "FdvGQcJikzAKCnoSfwIrR+" } } */;
SELECT ("Extract"."#fmc_vav_ac_1_PackageUnit_measure_heartbeat_alive_real_path" || "Extract"."#fmc_vav_ac_2_PackageUnit_measure_heartbeat_alive_real_path") AS "Calculation_5000613104827374",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_32_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_32_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_17_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_17_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_18_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_18_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_22_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_22_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_23_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_23_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_24_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_24_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_25_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_25_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_26_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_26_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_28_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_28_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_29_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_29_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_30_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_30_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_31_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_31_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_32_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_32_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_33_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_33_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_14_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_14_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_15_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_15_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_16_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_16_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_17_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_17_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_18_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_18_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_19_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_19_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_20_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_20_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_21_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_21_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_22_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_22_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_23_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_23_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_24_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_24_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_25_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_25_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_26_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_26_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_27_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_27_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_28_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_28_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_29_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_29_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_30_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_30_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_31_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_31_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_32_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_32_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_33_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_33_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_34_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_34_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_35_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_35_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_36_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_36_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_37_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_37_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_38_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_38_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_42_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_42_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_17_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_17_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_18_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_18_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_22_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_22_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_23_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_23_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_24_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_24_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_25_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_25_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_27_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_27_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_28_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_28_VAVR_Space:ok",
  SUM("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_29_VAVR_Space") AS "sum:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_29_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_01_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_01_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_02_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_02_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_03_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_03_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_04_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_04_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_05_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_05_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_06_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_06_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_07_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_07_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_08_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_08_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_09_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_09_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_10_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_10_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_11_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_11_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_12_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_12_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_13_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_13_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_14_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_14_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_15_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_15_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_16_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_16_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_19_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_19_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_20_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_20_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_21_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_21_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_27_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_27_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_34_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_34_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_36_VAVC_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_36_VAVC_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_01_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_01_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_02_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_02_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_03_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_03_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_04_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_04_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_05_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_05_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_06_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_06_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_07_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_07_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_08_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_08_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_09_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_09_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_10_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_10_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_11_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_11_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_12_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_12_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_13_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_13_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_41_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_41_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_43_VAVC_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_43_VAVC_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_47_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_47_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_a_VAVC_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_a_VAVC_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_01_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_01_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_02_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_02_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_03_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_03_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_04_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_04_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_05_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_05_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_06_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_06_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_07_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_07_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_08_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_08_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_09_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_09_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_10_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_10_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_11_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_11_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_12_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_12_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_13_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_13_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_14_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_14_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_15_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_15_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_16_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_16_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_19_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_19_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_20_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_20_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_21_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_21_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_34_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_34_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_37_VAVR_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_37_VAVR_Space:ok",
  SUM("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_38_VAVC_Space") AS "sum:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_38_VAVC_Space:ok",
  "Extract"."time" AS "time"
FROM "Extract"."Extract" "Extract"
WHERE (((CAST(TRUNC(EXTRACT(HOUR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) IN (7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17)) AND (CASE WHEN ((((CAST(TRUNC(EXTRACT(YEAR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) * 10000) + (CAST(TRUNC(EXTRACT(MONTH FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) * 100)) + CAST(TRUNC(EXTRACT(DAY FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL)) IN (20140512, 20140513, 20140514, 20140515, 20140516, 20140517, 20140518, 20140519, 20140520, 20140608, 20140609, 20140610)) THEN FALSE ELSE TRUE END)) AND (("Extract"."#fmc_vav_ac_1_PackageUnit_measure_heartbeat_alive_real_path" || "Extract"."#fmc_vav_ac_2_PackageUnit_measure_heartbeat_alive_real_path") IN ('1.0001.000', 'nannan')))
GROUP BY 1,
  112
/* { "tableau-query-origins": { "query-category": "Data", "lqctx-root-activity-id": "FdvGQcJikzAKCnoSfwIrR+", "lqctx-batch-query-id": "1" } } */;
SELECT (1 + CAST(TRUNC(DATE_PART('DOW', TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL)) AS "wd:time:ok"
FROM "Extract"."Extract" "Extract"
GROUP BY 1
/* { "tableau-query-origins": { "query-category": "QuickFilter", "lqctx-root-activity-id": "Po+vwukZ0qsIzdhte+d338", "lqctx-batch-query-id": "1" } } */;
SELECT ("Extract"."#fmc_vav_ac_1_PackageUnit_measure_heartbeat_alive_real_path" || "Extract"."#fmc_vav_ac_2_PackageUnit_measure_heartbeat_alive_real_path") AS "Calculation_5000613104827374",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_17_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_17_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_18_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_18_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_22_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_22_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_23_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_23_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_24_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_24_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_25_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_25_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_26_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_26_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_28_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_28_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_29_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_29_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_30_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_30_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_31_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_31_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_32_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_32_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_33_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_33_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_14_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_14_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_15_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_15_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_16_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_16_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_17_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_17_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_18_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_18_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_19_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_19_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_20_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_20_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_21_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_21_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_22_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_22_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_23_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_23_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_24_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_24_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_25_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_25_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_26_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_26_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_27_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_27_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_28_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_28_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_29_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_29_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_30_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_30_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_31_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_31_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_32_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_32_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_33_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_33_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_34_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_34_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_35_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_35_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_36_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_36_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_37_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_37_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_38_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_38_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_42_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_42_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_17_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_17_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_18_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_18_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_22_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_22_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_23_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_23_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_24_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_24_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_25_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_25_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_27_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_27_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_28_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_28_VAVR_Space:ok",
  AVG(CAST("Extract"."AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_29_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC1-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_29_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_01_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_01_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_02_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_02_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_03_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_03_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_04_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_04_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_05_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_05_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_06_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_06_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_07_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_07_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_08_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_08_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_09_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_09_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_10_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_10_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_11_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_11_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_12_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_12_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_13_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_13_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_14_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_14_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_15_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_15_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_16_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_16_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_19_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_19_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_20_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_20_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_21_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_21_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_27_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_27_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_34_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_34_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_36_VAVC_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_1_36_VAVC_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_01_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_01_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_02_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_02_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_03_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_03_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_04_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_04_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_05_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_05_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_06_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_06_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_07_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_07_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_08_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_08_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_09_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_09_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_10_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_10_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_11_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_11_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_12_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_12_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_13_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_13_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_41_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_41_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_43_VAVC_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_43_VAVC_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_47_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_47_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_a_VAVC_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_2_a_VAVC_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_01_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_01_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_02_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_02_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_03_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_03_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_04_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_04_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_05_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_05_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_06_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_06_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_07_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_07_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_08_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_08_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_09_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_09_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_10_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_10_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_11_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_11_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_12_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_12_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_13_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_13_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_14_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_14_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_15_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_15_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_16_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_16_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_19_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_19_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_20_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_20_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_21_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_21_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_34_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_34_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_37_VAVR_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_37_VAVR_Space:ok",
  AVG(CAST("Extract"."AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_38_VAVC_Space" AS DOUBLE PRECISION OR NULL)) AS "avg:AC2-ThermalSpaceExcursionValidator_clg_#fmc_vav_3_38_VAVC_Space:ok"
FROM "Extract"."Extract" "Extract"
WHERE (((CAST(TRUNC(EXTRACT(HOUR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) IN (8, 9, 10, 11, 12, 13, 14, 15, 16, 17)) AND (CASE WHEN ((((CAST(TRUNC(EXTRACT(YEAR FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) * 10000) + (CAST(TRUNC(EXTRACT(MONTH FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL) * 100)) + CAST(TRUNC(EXTRACT(DAY FROM TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL)) IN (20140512, 20140513, 20140514, 20140515, 20140516, 20140517, 20140518, 20140519, 20140520, 20140608, 20140609, 20140610)) THEN FALSE ELSE TRUE END) AND ((1 + CAST(TRUNC(DATE_PART('DOW', TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL)) >= 2) AND ((1 + CAST(TRUNC(DATE_PART('DOW', TABLEAU.NORMALIZE_DATETIME("Extract"."time"))) AS BIGINT OR NULL)) <= 6)) AND (("Extract"."#fmc_vav_ac_1_PackageUnit_measure_heartbeat_alive_real_path" || "Extract"."#fmc_vav_ac_2_PackageUnit_measure_heartbeat_alive_real_path") IN ('1.0001.000', 'nannan')))
GROUP BY 1
/* { "tableau-query-origins": { "query-category": "Data", "lqctx-root-activity-id": "M02u3eEgEkvLx3fsLRVfcd", "lqctx-batch-query-id": "2" } } */;
