COPY "Extract"."Extract" FROM '' (format csv, delimiter '|', null '');
CREATE  TABLE "#Tableau_2_1CE95DD4-5F0C-489A-A24E-1B433FD03A17_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
CREATE  TABLE "#Tableau_3_D7115E80-5904-443E-A35D-2B6D16B5C3EB_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
CREATE  TABLE "#Tableau_1_B9E202DA-A5B7-47C7-8161-66601690EF01_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
CREATE  TABLE "#Tableau_4_8E0BC4D8-E490-4364-BE64-0AF6B8346940_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
CREATE  TABLE "#Tableau_5_5B727BED-CE2C-4D43-BCAB-1BD8BF66B034_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
CREATE  TABLE "#Tableau_6_DC25525A-E369-43ED-BBC3-D527CFADAF74_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
CREATE  TABLE "#Tableau_7_C651BCD6-BD84-4671-9B62-5940C23C0BCE_1_Filter" AS
SELECT "Extract"."Charter School" AS "Charter School",
  "Extract"."Childcare_Center_Type" AS "Childcare_Center_Type",
  "Extract"."District_Name" AS "District_Name",
  "Extract"."Grade Span" AS "Grade Span",
  "Extract"."Latitude" AS "Latitude",
  "Extract"."Letter_Grade_Combined" AS "Letter_Grade_Combined",
  "Extract"."Longitude" AS "Longitude",
  "Extract"."Magnet_App_Process" AS "Magnet_App_Process",
  "Extract"."Magnet_Primary" AS "Magnet_Primary",
  "Extract"."Magnet_Secondary" AS "Magnet_Secondary",
  "Extract"."Magnet_Tertiary" AS "Magnet_Tertiary",
  "Extract"."Religious_Orientation" AS "Religious_Orientation",
  "Extract"."School_Email_Address" AS "School_Email_Address",
  "Extract"."School_Name" AS "School_Name",
  "Extract"."School_Phone" AS "School_Phone",
  "Extract"."School_Site_City" AS "School_Site_City",
  "Extract"."School_Site_State" AS "School_Site_State",
  "Extract"."School_Site_Street_Address" AS "School_Site_Street_Address",
  "Extract"."School_Site_Zip" AS "School_Site_Zip",
  "Extract"."School Type" AS "School Type",
  "Extract"."School_Web_Page_Address" AS "School_Web_Page_Address"
FROM "Extract"."Extract" "Extract"
LIMIT 0;
