#!/usr/bin/env bash

# This is a wrapper around hyperd to start it without a password
ARGS=( "$@" )
for i in "${!ARGS[@]}"; do
    if [[ ${ARGS[$i]} == "--no-password=false" ]]; then
        ARGS[$i]="--no-password=true"
    fi
done
"/Applications/Tableau Public.app/Contents/MacOS/hyper/hyperd.original" "${ARGS[@]}"
