CREATE SCHEMA "Extract";
CREATE TABLE "Extract"."Extract" (
"Ato Impugnado" TEXT,
"Beneficiados (2)" TEXT,
"Beneficiados (prov)" TEXT,
"Classe" TEXT,
"Código Requerente" TEXT,
"Data da Distribuicao (BNDPJ) (Month / Year)" INT,
"Data da Distribuicao (BNDPJ) (Years)" DATE,
"Data da Distribuicao (BNDPJ)" DATE,
"Data da Liminar (Years)" DATE,
"Data da Liminar" DATE,
"Data do Julgamento do mérito (Years)" DATE,
"Data do Julgamento do mérito" DATE,
"Duração do processo" DOUBLE PRECISION,
"Estadual contra estadual" TEXT,
"F14" TEXT,
"F49" TEXT,
"Fundamento (Código)" TEXT,
"Julgamento do merito (completo)" TEXT,
"Julgamento do merito (julgados)" TEXT,
"Julgamento do merito (procedencia)" TEXT,
"Numero" DOUBLE PRECISION,
"Origem do ato impugnado" TEXT,
"Origem do requerente" TEXT,
"Relator em 2013" TEXT,
"Requerente" TEXT,
"Requerentes (outros)" TEXT,
"Resultado da Liminar" TEXT
);
