CREATE SCHEMA "Extract";
CREATE TABLE "Extract"."Extract" (
"1.32" DOUBLE PRECISION,
"2ndangle" DOUBLE PRECISION,
"AdjDist" DOUBLE PRECISION,
"Adjacent" BIGINT,
"AwayT" TEXT,
"BR ID" BIGINT,
"BR Jersey" TEXT,
"BegXPass" BIGINT,
"BegYPass" BIGINT,
"CategoryEn=" TEXT,
"CategoryID=" BIGINT,
"Date" DATE,
"EndX" BIGINT,
"EndXpass" BIGINT,
"EndYPass" BIGINT,
"EndY" BIGINT,
"EventAfterBR" BIGINT,
"EventEn=" TEXT,
"EventID=" BIGINT,
"EventID" BIGINT,
"ExtraEn=" TEXT,
"ExtraID=" BIGINT,
"Firstangle" DOUBLE PRECISION,
"From-To Names" TEXT,
"From-To" TEXT,
"GF Away" BIGINT,
"GF Home" BIGINT,
"GS" BIGINT,
"Half=" BIGINT,
"HomeT" TEXT,
"Is 1-1" BIGINT,
"Is AssistNA" BIGINT,
"Is Assist" BIGINT,
"Is BR" BIGINT,
"Is CP" BIGINT,
"Is DFK" BIGINT,
"Is FinalThirdPass" BIGINT,
"Is KP" BIGINT,
"Is Unique" BIGINT,
"IsGK=" DATE,
"IsKPNA" BIGINT,
"Jersey" TEXT,
"KP BR" BIGINT,
"MatchID" BIGINT,
"Minutes" BIGINT,
"Opposite" BIGINT,
"Pass ID" BIGINT,
"PassAngle" TEXT,
"PassDistance" DOUBLE PRECISION,
"PassOutcome" TEXT,
"PasserID" BIGINT,
"PathID" BIGINT,
"PathOrder" BIGINT,
"PlayerID=" BIGINT,
"PlayerName" TEXT,
"Position" BIGINT,
"PossType" BIGINT,
"ReceiveEvent" BIGINT,
"ReceiveID" BIGINT,
"ResultEn=" TEXT,
"ResultID=" BIGINT,
"ShotID" BIGINT,
"Team" TEXT,
"Time=" TIMESTAMP,
"Timestamp" TIMESTAMP,
"Vs" TEXT,
"X=" BIGINT,
"Y=" BIGINT,
"YardsR" DOUBLE PRECISION,
"realminute" DOUBLE PRECISION,
"realtime" TIMESTAMP,
"relative" DOUBLE PRECISION,
"xA" DOUBLE PRECISION,
"xG" DOUBLE PRECISION
);
